name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      VITE_TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Build Storybook
        run: bun build-storybook
      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
